[package]
name = "hades-events"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Internal event system for Hades"

[dependencies]
tokio.workspace = true
serde.workspace = true
chrono.workspace = true
thiserror.workspace = true
tracing.workspace = true
